[package]
name = "pdbextract"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
pdb = "0.2.0"
failure = "0.1.1"
regex = "0.2"
lazy_static = "1.0"

[profile.release]
debug = true
debug-assertions = true
